version: '3.4'

services:
  scorecardapollobackend:
    image: scorecardapollobackend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scorecardBackend
    env_file: 
      - .env
    networks: 
      - net_scorecard_backend
    ports:
      - 8000:8000
  redis-server:
    image: redis
    container_name: redis-server
    networks: 
      - net_scorecard_backend

networks: 
  net_scorecard_backend:
    external: true